pod 'Masonry', '0.6.1'
pod 'AFNetworking', '~> 3.0.4'
pod 'libextobjc', '~> 0.4.1'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh', '~> 3.1.0'
pod 'UITextView+Placeholder'
pod 'SDWebImage', '~> 3.7.3'
pod 'CocoaLumberjack', '~> 2.2'
pod 'BlocksKit', '~> 2.2.5'
pod 'JSONModel', '~> 1.2.0'
pod 'NSDate-Additions', '~> 0.0.10'
pod 'RETableViewManager', '~> 1.7'
